name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' # Specify the Node.js version

      - name: set lower case repo name
        id: repo-name
        run: echo "REPO_LC=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        env:
          REPO_LC: ${{ steps.repo-name.outputs.REPO_LC }}
        run: |
          docker build -t ghcr.io/${{ env.REPO_LC }}/headers-app:latest .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        env:
          REPO_LC: ${{ steps.repo-name.outputs.REPO_LC }}
        run: |
          docker push ghcr.io/${{ env.REPO_LC }}/headers-app:latest